services:
  mariadb:
    image: mariadb
    container_name: c_mariadb
    environment:
      - MARIADB_USER=userbd
      - MARIADB_PASSWORD=1234
      - MARIADB_DATABASE=mabase
      - MARIADB_ROOT_PASSWORD=test123
    ports:
      - "3306:3306"

  monapache:
    image: davidnabel/mon_apache
    ports:
      - "80:80"

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - "8080:80"

  monubuntu:
    image: davidnabel/monubuntu